name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.13.11-alpine3.10
    steps:
      - name: Install cgo dependencies
        run: apk add --no-cache build-base
      - name: Checkout
        uses: actions/checkout@master
      - name: Test
        run: go test ./...
